"""
This type stub file was generated by pyright.
"""

import os
import pathlib
import platform
import shutil
import sys
import matplotlib
from ._pcraster import *
from .operations import *
from . import operators
from .aguila import *
from .numpy_operations import *
from .__about__ import __author__, __copyright__, __license__, __uri__, __version__
from ._pcraster_modflow import *
from .multicore import *
from .matplotlib import plot

if sys.platform == "win32":
    pcraster_app_path = ...
_var = ...
_workers = ...
