"""
This type stub file was generated by pyright.
"""

import threading

class AguilaThread(threading.Thread):
    def __init__(self, *arguments, **keywords) -> None:
        ...
    
    def __del__(self) -> None:
        ...
    
    def parse_arguments(self, arguments) -> list[Any]:
        ...
    
    def run(self) -> None:
        ...
    


def aguila(*arguments, **keywords) -> None:
    """
    Each argument is taken to be a raster or a list of rasters. Each raster
    should be the name of a raster file on disk or a variable resulting
    from a PCRaster operation.

    Individual rasters end up in separate visualisation windows. The rasters
    from a list of rasters ends in a single visualisation window.
    """
    ...

