"""
This type stub file was generated by pyright.
"""

def plot(raster, labels=..., title=..., filename=...) -> None:
    """

    ``raster``: Raster map with type of either Boolean, Nominal, Scalar, or Ldd.

    ``labels``: Optional. Dictionary of labels that should be used for the legend, cell values will be used otherwise.

    ``title``: Optional. Legend title, tries to identify the variable name otherwise.

    ``filename``: Optional. If provided plot will be written to disk.

    Creates a plot of a PCRaster map using matplotlib. The plot is either opened in a separate window, or written to disk in case a filename is provided.

    .. versionadded:: 4.3

    .. note::
       This function is only available when the ``matplotlib`` module is installed.
    """
    ...

