"""
This type stub file was generated by pyright.
"""

def pcr2numpy(map, mv):
    """
    Convert entities from PCRaster to NumPy.

    map -- Map you want to convert.

    mv -- Value to use in the result array cells as a missing value.

    Returns an array.
    """
    ...

def numpy2pcr(dataType, array, mv):
    """
    Convert entities from NumPy to PCRaster.

    dataType -- Either Boolean, Nominal, Ordinal, Scalar, Directional or Ldd.

    array -- Array you want to convert.

    mv -- Value that identifies a missing value in the array.

    Returns a map.
    """
    ...

def pcr_as_numpy(map):
    """
    Reference PCRaster maps from NumPy arrays.

    map -- Map to reference.

    Returns an array.
    """
    ...

