"""
This type stub file was generated by pyright.
"""

Error = ...
class Exception(Exception):
  def __init__(self, message) -> None:
    ...
  


class StdoutTee:
  def __init__(self, fileName, openMode) -> None:
    ...
  
  def write(self, string) -> None:
    ...
  
  def flush(self) -> None:
    ...
  


EXEMODE = ...
DIRMODE = ...
FILEMODE = ...
def message(msg) -> None:
  ...

def warning(msg) -> None:
  ...

def error(msg) -> None:
  ...

def write(msg) -> None:
  ...

def testNonEmptyFile(p) -> None:
  ...

def processFiles(dir, func) -> None:
  ...

def processDirs(dir, func) -> None:
  ...

def dateString() -> str:
  ...

def timeString() -> str:
  ...

def createArchive(dir) -> None:
  ...

def replaceCase(caseTypes, str, wordToReplace, replaceWithWord):
  ...

def normalizeText(str, nl=...) -> str:
  ...

def containsWhiteSpace(str) -> bool:
  ...

def pcrtree(*path) -> str:
  ...

def devenv(*path) -> str:
  ...

def pcrtreeRelativePath(absPath):
  """ path of absPath relative to PCRTREE env. variable:\n
     PCRTREE=/home/cees/pcrtree
     absPath=/home/cees/pcrtree/libs/pcrme/calc_test.cc
     will return libs/pcrme/calc_test.cc

    *Under Windows the return path is also ALWAYS with "/"!
    *Under Cygwin all output options are accepted for absPath
     --windows c:\d\pcrtree
     --mixed   c:/d/pcrtree
     --unix    /cygdrive/c/d/pcrtree
 """
  ...

def python2() -> bool:
  ...

def python24() -> bool:
  ...

if not python24():
  def execute(cmd, bufferSize=...) -> list[str]:
    ...
  
else:
  class ExecNoStdin:
    def __init__(self, cmd) -> None:
      ...
    
    def stdoutEmpty(self) -> bool:
      ...
    
    def stderrEmpty(self) -> bool:
      ...
    
    def stdoutLines(self) -> list[bytes]:
      ...
    
    def stdoutText(self):
      ...
    
    def stderrLines(self) -> list[bytes]:
      ...
    
    def stderrText(self):
      ...
    
    def exitStatus(self) -> int:
      ...
    
  
  
  def popenWrapper(cmd, bufferSize=...) -> PopenWrapperReturn:
    class PopenWrapperReturn:
      ...
    
    
  
  def executeOneLine(cmd):
    ...
  
  def execute(cmd, bufferSize=...) -> list[Any]:
    """ execute command and
         - return stdout as list of strings
         - raise  pcr.Exception on non-0 exit code or any other error condition
         - cache stderr, if pcr.Exception is raised then str() on this
           exception yield the stderr output
    """
    ...
  
def listConc(src) -> list[Any]:
  ...

def listAppend(dest, *listsToAppend):
  ...

def pathJoin(pathNames) -> str:
  ...

def pathNameToUrl(pathName):
  ...

def testOpenForReading(pathName) -> None:
  ...

def testOpenForWriting(pathName) -> None:
  ...

def testFileDoesNotExist(pathName) -> None:
  ...

def searchFileUpTree(directory, fileToFind):
  ...

def hasOnlyChild(node, name) -> bool:
  ...

def getOnlyChild(node, name):
  ...

def expandEnvVars(path):
  ...

def findExecutable(fileName) -> str:
  ...

def replaceFromFile(fileName, searchStrings, replaceStrings) -> str:
  ...

def replaceFromString(sourceString, searchStrings, replaceStrings):
  ...

def removeDuplicates(oldList) -> list[Any]:
  ...

def isValidEmailAddress(address) -> Literal[0, 1]:
  ...

def createMailMessage(fromAddress, toAddress, subject, text):
  ...

def log(fileName, msg) -> None:
  ...

def discover(dirsWithMakefile, path, names) -> None:
  ...

def relPathUp(directory) -> LiteralString | Literal['.']:
  ...

def createTempDirectory(name):
  ...

def clVimFilter(msgs) -> LiteralString:
  ...

