"""
This type stub file was generated by pyright.
"""

from pcraster import *

def selectSArray(name, sampleNumbers, row, col) -> NDArray[floating[_32Bit]]:
  """Selects values at row, col from raster name in Monte Carlo samples.

  name -- Name of raster.
  sampleNumber -- Numbers of MC samples to use.
  row -- Row index of cell to read.
  col -- Col index of cell to read.
  The returned array does not contain missing values so the size is maximimal
  sampleNumbers but possibly smaller.

  Returned array has elements of type numpy.float32"""
  ...

def selectSArrays(name, sampleNumbers) -> list[Any]:
  ...

def aggregateSPerCell(name, sampleNumbers, calculator):
  ...

def aggregateS(name, sampleNumbers, calculator):
  ...

class PercentileCalculator:
  def __init__(self, percentiles) -> None:
    ...
  
  def run(self, arrays) -> None:
    ...
  
  def result(self) -> list[Any]:
    ...
  


def probability(name, sampleNumbers):
  """
  Calculates the probability that a cell is TRUE.

  name
    Name of the (boolean) raster for which each sample has a realization.

  sampleNumbers
    List of numbers of samples to aggregate.

  Returns a raster with probabilities.
  """
  ...

def average(name, sampleNumbers):
  """
  Calculates the average value of each cell.

  name
    Name of the scalar raster for which each sample has a realization.

  sampleNumbers
    List of numbers of samples to aggregate.

  Returns a raster with average values.
  """
  ...

def variance(name, sampleNumbers):
  """
  Calculates the variance of each cell.

  name
    Name of the scalar raster for which each sample has a realization.

  sampleNumbers
    List of numbers of samples to aggregate.

  Returns a raster with variances.
  """
  ...

def stddev(name, sampleNumbers):
  """
  Calculates the standard deviation of each cell.

  name
    Name of the scalar raster for which each sample has a realization.

  sampleNumbers
    List of numbers of samples to aggregate.

  Returns a raster with standard deviations.
  """
  ...

def percentile(name, sampleNumbers, percentiles) -> list[Any]:
  """
  Calculates a percentile for each cell.

  name
    Name of the scalar raster for which each sample has a realization.

  sampleNumbers
    List of numbers of samples to aggregate.

  percentiles
    Percentile or list of percentiles to calculate. Percentiles range from
    [0.0, 1.0].

  Returns a raster or a list of rasters with percentiles.
  """
  ...

def timeseries(name, timeSteps, row, col) -> tuple[NDArray[signedinteger[_32Bit]], NDArray[floating[_32Bit]]]:
  ...

def correlation(location, independentName, dependentName, locationName, sampleNumbers, timeSteps) -> None:
  ...

def staticInput(timeSteps) -> Literal[False]:
  ...

def deterministicInput(sampleNumbers) -> Literal[False]:
  ...

def sampleMin(name, sampleNumbers):
  """
  Calculates the minimum value of each cell.

  name
    Name of the scalar raster for which each sample has a realization.

  sampleNumbers
    List of numbers of samples to aggregate.

  Returns a raster with minimum values.
  """
  ...

def sampleMax(name, sampleNumbers):
  """
  Calculates the maximum value of each cell.

  name
    Name of the scalar raster for which each sample has a realization.

  sampleNumbers
    List of numbers of samples to aggregate.

  Returns a raster with maximum values.
  """
  ...

def uniquesamples(name, sampleNumbers) -> tuple[int, list[Any]]:
  """
  Retrieves the unique samples.

  name
    Name of the raster for which each sample has a realization.

  sampleNumbers
    List of numbers of samples to aggregate.

  Returns a list with sets of corresponding loops.
  """
  ...

def mcaveragevariance(names, sampleNumbers, timeSteps) -> None:
  ...

def mcpercentiles(names, percentiles, sampleNumbers, timeSteps) -> None:
  ...

def createtimeseries(names, nameExtension, locations, sampleNumbers, timeSteps) -> None:
  ...

def createtimeseriesnewfileformat(names, locations, sampleNumbers, timeSteps, quantiles) -> None:
  ...

def createGstatRealizations(setOfRealizations, nameCommandFile, nameOutMapList) -> None:
  ...

def createAllGstatRealizations(nameCommandFile, nameOutMapList, nrRealPerGstatCall, sampleNumbers, timeSteps) -> None:
  ...

