"""
This type stub file was generated by pyright.
"""

from . import dynamicBase

class DynamicModel(dynamicBase.DynamicBase):
  def __init__(self) -> None:
    ...
  
  def initial(self) -> None:
    ...
  
  def dynamic(self) -> None:
    ...
  
  def timeSteps(self) -> range:
    """
    Return a list of time steps configured
    """
    ...
  
  def nrTimeSteps(self) -> int:
    """
    Return the number of time steps
    """
    ...
  
  def currentTimeStep(self) -> int:
    """
    Return the current time step in the range from firstTimeStep to nrTimeSteps.
    """
    ...
  
  def firstTimeStep(self) -> int:
    """
    Return first timestep of a model.
    """
    ...
  
  def report(self, variable, name) -> None:
    """
    Storing map data to disk

    `variable`
      Variable containing the PCRaster map data

    `name`
      Name used as filename. Use a filename with less than eight
      characters and without extension. File extension for dynamic models
      is ".map" in the initial section and the 8.3 style format name in
      the dynamic section. File extensions will be appended automatically.
    """
    ...
  
  def readmap(self, name, style=...):
    """
    Read map data from disk.

    `name`
      Name used as filename. Use filename with less than eight characters
      and without extension. File extension for dynamic models is ".map"
      in initial section and the 8.3 style format name in the dynamic
      section. File extensions will be appended automatically.

    .. todo::

      `style` argument is not used.
    """
    ...
  


