"""
This type stub file was generated by pyright.
"""

from . import frameworkBase

class DynamicFramework(frameworkBase.FrameworkBase):
  """
  Framework class for dynamic models.

  `userModel`
    Instance that models the :ref:`Dynamic Model Concept <dynamicModelConcept>`.

  `lastTimeStep`
    Last timestep to run.

  `firstTimestep`
    Sets the starting timestep of the model (optional, default is 1).
  """
  def __init__(self, userModel, lastTimeStep=..., firstTimestep=...) -> None:
    ...
  
  def run(self) -> Literal[0]:
    """
    Run the dynamic user model.

    .. todo::

      This method depends on the filter frameworks concept. Shouldn't its run
      method call _runSuspend()?
    """
    ...
  
  def setQuiet(self, quiet=...) -> None:
    """
    Disables the progress display of timesteps.
    """
    ...
  


