"""
This type stub file was generated by pyright.
"""

class DynamicBase:
  """
  Base class for DynamicModel framework class.

  .. todo::

    KDJ: What is the reason this class exists? Can it be merged with
    DynamicModel?
  """
  def __init__(self) -> None:
    ...
  
  def setDebug(self):
    ...
  
  def initial(self):
    """  """
    ...
  
  def dynamic(self):
    """  """
    ...
  
  def timeSteps(self):
    """  """
    ...
  
  def nrTimeSteps(self):
    """  """
    ...
  
  def firstTimeStep(self):
    """
    Return the first timestep that is executed.
    """
    ...
  
  def setQuiet(self, quiet=...) -> None:
    """
    Disables the progress display of timesteps.
    """
    ...
  
  def currentTimeStep(self):
    """  """
    ...
  


