"""
This type stub file was generated by pyright.
"""

"""Functionality for applications with sub processes."""
class ChildProcess:
  """Class to represent child processes."""
  def __init__(self, name, pid) -> None:
    """Constructor.

    name -- Name of the process.

    pid -- Process id of the process.

    Upon creation the start time of the process will be set."""
    ...
  
  def stopped(self, result) -> None:
    """Sets the end time and the result of the process.

    result -- Result.

    Should be called after the process stopped executing."""
    ...
  
  def pid(self) -> Any:
    """Returns the process id."""
    ...
  
  def name(self) -> Any:
    """Returns the name."""
    ...
  
  def exitedWithZeroStatus(self) -> bool:
    """Returns whether or not the process exited with status 0."""
    ...
  
  def duration(self) -> float:
    """Returns the duration of the process as an amount of seconds."""
    ...
  
  def durationAsString(self) -> str:
    """Returns the duration of the process as a string."""
    ...
  
  def message(self) -> str:
    """Returns a message with result information of the process.

    Should only be called after the process stopped executing."""
    ...
  


class ForkScript:
  def __init__(self) -> None:
    ...
  
  def __del__(self) -> None:
    ...
  
  def isParentProcess(self) -> bool:
    ...
  
  def isChildProcess(self) -> bool:
    ...
  
  def childProcesses(self) -> list[Any]:
    ...
  
  def nrChildProcesses(self) -> int:
    ...
  
  def nrForkedChildProcesses(self) -> int:
    ...
  
  def nrFinishedChildProcesses(self) -> int:
    ...
  
  def nrFailedChildProcesses(self) -> int:
    ...
  
  def setSleepTimeDecayFactor(self, decayFactor) -> None:
    ...
  
  def fork(self, name) -> int:
    ...
  
  def handleFinishedChildProcess(self, process, result) -> None:
    ...
  
  def handleFinishedChildProcesses(self) -> list[Any]:
    """Performs some administratives in case child processes have finished."""
    ...
  
  def waitForChildProcessesToFinish(self) -> list[Any]:
    """Waits for the current child processes to finish.

    Also performs some administratives.
    """
    ...
  
  def averageChildProcessDuration(self, lastNrSamplesToUse) -> float:
    ...
  
  def sleepTime(self) -> float | int:
    ...
  


