"""
This type stub file was generated by pyright.
"""

from . import shellscript

class WeakCallback:
  """A Weak Callback object that will keep a reference to
    the connecting object with weakref semantics.

    This allows object A to pass a callback method to object S,
    without object S keeping A alive.
    """
  def __init__(self, mcallback) -> None:
    """Create a new Weak Callback calling the method @mcallback"""
    ...
  
  def __call__(self, *args, **kwargs) -> Any:
    ...
  
  def default_callback(self, *args, **kwargs):
    """Called instead of callback when expired"""
    ...
  
  def object_deleted(self, wref) -> None:
    """Called when callback expires"""
    ...
  


def generateNameT(name, time) -> str:
  """
  Return a filename based on the name and time step passed in.

  The resulting name obeys the 8.3 DOS style format. The time step
  will be added to the end of the filename and be prepended by 0's if
  needed.

  The time step normally ranges from [1, nrTimeSteps].
  The length of the name should be max 8 characters to leave room for
  the time step.

  The name passed in may contain a directory name.

  See also: generateNameS(), generateNameST()
  """
  ...

def generateNameS(name, sample):
  """Return a filename based on the name and sample number passed in.

  The resulting name contains a directory and a filename part. The
  sample number is used as the directory name and the name is used as
  the filename.

  The sample number normally ranges from [1, nrSamples].

  See also: generateNameT(), generateNameST()
  """
  ...

def generateNameST(name, sample, timestep):
  """
  Return a filename based on the name, sample number and time step.

  See also: generateNameT(), generateNameS()
  """
  ...

class FrameworkBase(shellscript.ShellScript):
  """
  Base class for frameworks.

  Basically contains things for logging...
  """
  _d_quiet = ...
  _d_trace = ...
  _d_debug = ...
  _d_indentLevel = ...
  _d_inScript = ...
  _d_mapExtension = ...
  def __init__(self) -> None:
    ...
  
  def __del__(self) -> None:
    ...
  
  def setQuiet(self, quiet) -> None:
    """
    Enable/disable all framework output to stdout.

    `quiet`
      True/False. Default is set to False
    """
    ...
  
  def setTrace(self, trace) -> None:
    """
    Trace framework output to stdout.

    `trace`
      True/False. Default is set to False.

    If tracing is enabled the user will get a detailed framework output
    in an XML style.
    """
    ...
  
  def setDebug(self, debug) -> None:
    ...
  
  def generateNameS(self, name, sample):
    ...
  


class FrameworkError(Exception):
  def __init__(self, msg) -> None:
    ...
  
  def __str__(self) -> str:
    ...
  


