"""
This type stub file was generated by pyright.
"""

from pcraster import *

def getCellValue(Map, Row, Column) -> None:
  ...

def getCellValueAtBooleanLocation(location, map) -> None:
  ...

def printCellValue(self, mapVariable, variableNameToPrint, unit, row, column) -> None:
  ...

def onePeriod(self, startTime, endTime, timeStepDuration, currentTimeStep):
  ...

def mapeq(mapOne, mapTwo) -> None:
  ...

def slopeToDownstreamNeighbour(dem, ldd):
  ...

def slopeToDownstreamNeighbourNotFlat(dem, ldd, minSlope):
  ...

def distancetodownstreamcell(Ldd):
  ...

def createTimeSeriesList(timeSeriesFile) -> list[Any]:
  ...

def timeInputSparse(fileName) -> bool:
  ...

def normalcorrelated(normalX, normalY, correlation) -> tuple[Any, Any]:
  ...

