"""
This type stub file was generated by pyright.
"""

from . import frameworkBase

class EnsKalmanFilterFramework(frameworkBase.FrameworkBase):
  def __init__(self, userModel) -> None:
    ...
  
  def setObservedMatrices(self, observations, covariance) -> None:
    ...
  
  def setMeasurementOperator(self, matrix) -> None:
    ...
  
  def setFilterTimesteps(self, filterTimesteps) -> None:
    ...
  
  def filterTimesteps(self):
    ...
  
  def run(self) -> Literal[0]:
    ...
  
  def getStateVector(self, sampleNumber) -> Any:
    ...
  
  def readmap(self, name):
    ...
  
  def readDeterministic(self, name):
    ...
  


