"""
This type stub file was generated by pyright.
"""

class EnKfBase:
  def __init__(self) -> None:
    ...
  
  def initial(self):
    ...
  
  def setDebug(self):
    ...
  
  def setState(self):
    ...
  
  def setObservations(self):
    ...
  


