"""
This type stub file was generated by pyright.
"""

from . import kfBase

class EnKfModel(kfBase.EnKfBase):
  def __init__(self) -> None:
    ...
  
  def report(self, variable, name, style=...) -> None:
    ...
  
  def readmap(self, name, style=...):
    ...
  


