"""
This type stub file was generated by pyright.
"""

class MonteCarloBase:
  def __init__(self) -> None:
    ...
  
  def premcloop(self):
    ...
  
  def postmcloop(self):
    ...
  
  def nrSamples(self) -> int:
    """
    Return the number of samples
    """
    ...
  
  def currentSampleNumber(self) -> int:
    """
    Returns the current sample number
    """
    ...
  
  def sampleNumbers(self) -> range:
    """
    Returns a list of sample numbers configured
    """
    ...
  


