"""
This type stub file was generated by pyright.
"""

from . import forkscript, frameworkBase

class MonteCarloFramework(frameworkBase.FrameworkBase, forkscript.ForkScript):
  """
  Framework class for the Monte Carlo method.

  `userModel`
    Instance that models the :ref:`Monte Carlo Model Concept <monteCarloModelConcept>`.

  `nrSamples`
    Number of realisations to run.

  `remove_dirs`
    Flag whether sample directories should be removed
  """
  def __init__(self, userModel, nrSamples=..., remove_dirs=...) -> None:
    ...
  
  def setForkSamples(self, fork, nrCPUs=...) -> None:
    """
    Set the forking of samples on or off.

    `fork`
      True or False.

    `nrCPUs`
      Number of CPU's to use. If not provided, this is autodectected.

    When forking is on EVERY sample will be forked to its own
    process. This is mainly useful on a cluster with automatic
    process migration or on SMP machines.

    .. warning::

       setrandomseed does not work when forking is enabled

    .. note::

       Support for forking samples is not available on Windows

    .. todo::

       Implement a portable solution for forking.

    .. todo::

       Default nrCPUs should be <= 0. The user may want to use only 1 CPU (yes,
       silly).
    """
    ...
  
  def run(self, premc=..., postmc=...) -> Literal[0]:
    ...
  
  def setQuiet(self, quiet=...) -> None:
    """
    Disables the progress display of sample numbers.
    """
    ...
  


