"""
This type stub file was generated by pyright.
"""

from . import mcBase

class MonteCarloModel(mcBase.MonteCarloBase):
  def __init__(self) -> None:
    ...
  
  def premcloop(self) -> None:
    ...
  
  def postmcloop(self) -> None:
    ...
  
  def report(self, variable, name) -> None:
    """
    Report map data to disk.

    Standard extension is "map" in initial and timestep in the dynamic section.
    Output directory will be sample directory.
    """
    ...
  
  def readmap(self, name):
    """
    Read sample data from disk.

    Returns the map of the current time step from the current sample directory.
    """
    ...
  
  def readDeterministic(self, name):
    """
    Read deterministic data from disk.

    Returns the map of the file with current time step, from the current
    working directory.
    """
    ...
  


