"""
This type stub file was generated by pyright.
"""

from . import frameworkBase

class ParticleFilterFramework(frameworkBase.FrameworkBase):
  """
  Framework class for the particle filter method.

  `userModel`
    Instance that models the :ref:`Particle Filter Model Concept <particleFilterModelConcept>`.
  """
  def __init__(self, userModel) -> None:
    ...
  
  def setFilterTimesteps(self, filterTimesteps) -> None:
    """
    Set the filter moments.
    """
    ...
  
  def filterTimesteps(self):
    """
    Return a list of filter moments.
    """
    ...
  
  def run(self) -> Literal[0]:
    """
    Run the user model in the filter mode.

    Re-implemented from ShellScript.
    """
    ...
  
  def particleWeight(self, sample):
    """
    Return the weight of a particle.
    """
    ...
  
  def readmap(self, name):
    """
    Read sample data from disk.

    Returns the map of the current time step from the current sample directory.
    """
    ...
  
  def readDeterministic(self, name):
    """
    Read deterministic data from disk.

    Returns the map of the current time step from the current working directory.
    """
    ...
  


class SequentialImportanceResamplingFramework(ParticleFilterFramework):
  def __init__(self, userModel) -> None:
    ...
  
  def optimalSampleNumber(self, filterTimestep) -> Any:
    ...
  


class ResidualResamplingFramework(ParticleFilterFramework):
  def __init__(self, userModel) -> None:
    ...
  


