"""
This type stub file was generated by pyright.
"""

class ParticleFilterBase:
  def __init__(self) -> None:
    ...
  
  def setDebug(self):
    ...
  
  def filterPeriod(self) -> int:
    """
    Return the current filter period.
    """
    ...
  
  def filterTimesteps(self):
    ...
  
  def particleWeight(self):
    ...
  
  def reportState(self):
    ...
  
  def readState(self):
    ...
  


