"""
This type stub file was generated by pyright.
"""

from . import pfBase

class ParticleFilterModel(pfBase.ParticleFilterBase):
  def __init__(self) -> None:
    ...
  
  def reportState(self, variable, variableName) -> None:
    """
    Report a map into the state variable directory.
    """
    ...
  
  def readState(self, variableName):
    """
    Read a state variable map.
    """
    ...
  


