"""
This type stub file was generated by pyright.
"""

from numpy import *

def linearRegression(rawData, equationOrder) -> list[int]:
   ...

def regression(rawData, xEquationForm, yEquationForm=...) -> list[int]:
   ...

def linearRSquared(rawData, coefficients) -> float:
   ...

def solveRSquared(rawData, coefficients, xEquationForm, yEquationForm=...) -> float:
   ...

def gauss(AMatrix, BMatrix) -> list[int]:
   ...

