"""
This type stub file was generated by pyright.
"""

from . import staticBase

class StaticModel(staticBase.StaticBase):
  def __init__(self) -> None:
    """
    Base class for classes implementing the
    :ref:`Static Model Concept <staticModelConcept>`.
    """
    ...
  
  def initial(self) -> None:
    """
    Reimplemented from StaticBase.
    """
    ...
  
  def report(self, variable, name, style=...) -> None:
    """
    Store map data to disk

    `variable`
      object containing the PCRaster map data

    `name`
      name used as filename. Use filename without extension. File extension
      for deterministic static models is ".map" and will be appended
      automatically.

    .. todo::

      `style` argument is not used.
    """
    ...
  
  def readmap(self, name, style=...):
    """
    Read map data from disk.

    `name`
      name used as filename. Use filename without extension. File extension
      for deterministic static models is ".map" and will be appended
      automatically.

    .. todo::

      `style` argument is not used.
    """
    ...
  


