"""
This type stub file was generated by pyright.
"""

from . import frameworkBase

class StaticFramework(frameworkBase.FrameworkBase):
  """
  Framework class for static models.

  `userModel`
    Instance that models the :ref:`Static Model Concept <staticModelConcept>`.
  """
  def __init__(self, userModel) -> None:
    ...
  
  def run(self) -> Literal[0]:
    """
    Re-implemented from ShellScript.

    Run the execute or initial section of the user model.
    """
    ...
  


