"""
This type stub file was generated by pyright.
"""

class StaticBase:
  """
  Base class for StaticModel framework class.

  .. todo::

    KDJ: What is the reason this class exists? Can it be merged with
    StaticModel?
  """
  def __init__(self) -> None:
    ...
  
  def initial(self):
    """  """
    ...
  
  def setDebug(self):
    """  """
    ...
  


