"""
This type stub file was generated by pyright.
"""

class TimeoutputTimeseries:
  """
  Class to create pcrcalc timeoutput style timeseries
  """
  def __init__(self, tssFilename, model, idMap=..., noHeader=...) -> None:
    """

    """
    ...
  
  def sample(self, expression) -> None:
    """
    Sampling the current values of 'expression' at the given locations for the current timestep
    """
    ...
  


