"""
This type stub file was generated by pyright.
"""

class Index:
  """
  This class introduces the index type

  Parameters:

  values
    list of array-index names. The names must be CamelCased

  Example:

  PlantSpecies = Index([ "Species1", "Species2", "Species3" ])

  This introduces the index type 'PlantSpecies'. PlantSpecies (the type)
  has three names of type array-index: Species1, Species2 and Species3.
  """
  def __init__(self, values) -> None:
    ...
  
  def __setattr__(self, name, value):
    ...
  
  def __delattr__(self, value):
    ...
  
  def __getitem__(self, index):
    ...
  
  def __repr__(self) -> Any | Literal['']:
    ...
  


