"""
This type stub file was generated by pyright.
"""

class ValueFromParameterTable:
  """
  Class to be used for initialisation of collection indices from an external parameter file

  Parameter:

  varName

    name of the collection variable used in the external file

  fileName

    filename of the external file

  dataType

    PCRaster data type. Use None when reading maps from disk
  """
  def __init__(self, varName, fileName, dataType=...) -> None:
    ...
  
  def value(self, nrColumns, externalNames, keyDict) -> None:
    """
    returns the parameter value
    """
    ...
  


class ValueTimeoutputTimeseries:
  """
  Class to be used in initialisation of collection variables for timeseries output
  Parameters:

  varName
    name of the variable, used to generate the timeseries output filename

  model
    reference to the Dynamic or Static user model class

  idMap
    sample locations

  noHeader
    if False only column values will be written to file
  """
  def __init__(self, varName, model, idMap=..., noHeader=...) -> None:
    ...
  
  def value(self, keys):
    ...
  


class VariableCollection:
  """
  Creating arrayed variables

  Parameter:

  keys
    a list of Index classes

  value
    all array indices will be initialised with defaultValue.
    If defaultValue is a callable, the callable return value will be
    assigned to the collection item. The callable will be called with for each
    item in the collection with 2 arguments:

    name
      of this VariableCollection

    index
      index tuple of item a value is generated for

  Example:

  PlantSpecies = Index([ "Species1", "Species2"])

  Variable1 = VariableCollection([PlantSpecies], value=0)
  """
  def __init__(self, keys, value=...) -> None:
    ...
  
  def __getitem__(self, key):
    ...
  
  def __setitem__(self, key, value) -> None:
    ...
  
  def __iter__(self) -> Self:
    ...
  
  def next(self):
    """

    """
    ...
  
  __next__ = ...


